# -*- coding: utf-8 -*-
"""Untitled40.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aUnQF_x6fx-o7gDASxDtvgDCJTBDeexI
"""

from gpiozero import Servo
from gpiozero.pins.pigpio import PiGPIOFactory
import os
import time

# Use pigpio pin factory for more accurate PWM control
factory = PiGPIOFactory()

servo = Servo(17, pin_factory=factory)  # Attach the servo to GPIO pin 17 with pigpio

def control_soldier(command):
    # Move the servo to stand up when "አበበ" is spoken
    if "አበበ" in command:  # Amharic for "stand up"
        servo.max()  # Stand up position
        print("Soldier standing up")

    # Move the servo to lie down when "ከበደ" is spoken
    elif "ከበደ" in command:  # Amharic for "lay down"
        servo.min()  # Lie down position
        print("Soldier lying down")

    else:
        print("Unknown command:", command)

def read_command_from_file(file_path):
    if os.path.exists(file_path):
        with open(file_path, 'r') as file:
            command = file.read().strip()
        os.remove(file_path)  # Remove the file after reading the command
        return command
    return None

if __name__ == '__main__':
    try:
        file_path = '/home/pi/command_input.txt'  # Path where the laptop writes the command
        while True:
            command = read_command_from_file(file_path)
            if command:
                control_soldier(command)
            time.sleep(0.5)  # Check every 0.5 seconds for new commands
    except KeyboardInterrupt:
        print("Program exiting")